### ISSUE TITLE
The website seems to be down.

### ISSUE THREAD

**Issue by jtorreggiani** [tau-prolog/www.tau-prolog.org#1]
Visiting http://tau-prolog.org results in an error. 
<img width="1280" alt="Screen Shot 2019-11-12 at 6 41 35 PM" src="https://user-images.githubusercontent.com/4009178/68720059-09663c00-057c-11ea-9c83-3fcfa338da4d.png">
@jariazavalverde just wanted to bring this to your attention if it wasn't already.

**Comment by jariazavalverde** [comment]
Hi @jtorreggiani. Thanks for the notice.

We use a very basic web hosting service (FTP+PHP+MySQL), not a dedicated server, so usually when the page is down it is for some problem with the hosting company. All we can do is wait.

Right now I can access the website. Please let me know if the problem persists.
