### ISSUE TITLE
"More about asynchrony" link is empty

### ISSUE THREAD

**Issue by kuba-orlik** [tau-prolog/www.tau-prolog.org#2]
Clicking on the "More about asynchrony" link does not link to a new page

![image](https://user-images.githubusercontent.com/2697916/70315952-ef3a1980-181a-11ea-8dc5-17dbe528faf6.png)

**Comment by kuba-orlik** [comment]
Similarily, the link to async example in http://tau-prolog.org/manual/a-simple-tutorial leads to a 404 site at http://tau-prolog.org/manual/asynchronous-predicates

**Comment by jariazavalverde** [comment]
Hi @kuba-orlik.

These links should point to **[this section of the manual](https://github.com/tau-prolog/manual/blob/master/es/creando-tus-propios-paquetes.md)**, but it is only available in Spanish. It will be available in English in a few weeks.
