### ISSUE TITLE
JS library example code not working?

### ISSUE THREAD

**Issue by gilbert** [tau-prolog/www.tau-prolog.org#3]
I'm using the apply/3 example from [these docs](http://tau-prolog.org/documentation/prolog/js/apply/3):

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/17013/73589668-490f3680-448e-11ea-9336-25b02aa06462.png">

This happens on both Chrom and Safari.

**Comment by jariazavalverde** [comment]
Indeed, those examples are wrong. The `concat` method belongs to the `Array` prototype, not the global object. You should use `apply/4` instead:

```prolog
?- apply([], concat, [[1,2],[3,4]], Result). % == [].concat.apply([], [[1,2], [3,4]])
% Result = [1,2,3,4].

?- apply([0], concat, [[1,2],[3,4]], Result). % == [0].concat.apply([0], [[1,2], [3,4]])
% Result = [0,1,2,3,4].

% const succ = x => x+1;
?- prop(succ, Succ), apply([1,2,3], map, [Succ], Result). % == [1,2,3].map.apply([1,2,3], succ)
% Succ = <javascript>(function), Result = [2,3,4].
```

I just changed the examples on the website. Thanks for the report!
